version: '3'
services:
  backend:
    build: ./backend
    environment:
      ELECTRS_HOST: ${ELECTRS_HOST}
      ELECTRS_PORT: ${ELECTRS_PORT}
      ELECTRS_USE_SSL: ${ELECTRS_USE_SSL}
      ELECTRS_SSL_PORT: ${ELECTRS_SSL_PORT}
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"